<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RazorLangVersion>3.0</RazorLangVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>0.0.1-alpha.1</Version>
    <Authors>wzxinchen;Element-Blazor</Authors>
    <Company>Element-Blazor</Company>
    <Description>Admin template components for Element-Blazor.</Description>
    <PackageIcon>LOGO.png</PackageIcon>
    <PackageReadmeFile>PACKAGE_README.Admin.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/Element-Blazor/Element-Blazor/</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>Element,blazor,admin</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Templates\**" />
    <Content Remove="Templates\**" />
    <EmbeddedResource Remove="Templates\**" />
    <None Remove="Templates\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\LOGO.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="..\..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="PACKAGE_README.Admin.md">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="7.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="7.0.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Components\Element.csproj" />
    <ProjectReference Include="..\..\..\src\Markdown\Element.Markdown.csproj" />
  </ItemGroup>

</Project>
