<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
    <ApplicationIcon />
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
    <Description>Server-rendered admin template package for Element-Blazor.</Description>
    <Authors>wzxinchen;Element-Blazor</Authors>
    <StartupObject />
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Company>Element-Blazor</Company>
    <PackageProjectUrl>https://github.com/Element-Blazor/Element-Blazor/</PackageProjectUrl>
    <PackageIcon>LOGO.png</PackageIcon>
    <PackageReadmeFile>PACKAGE_README.Admin.ServerRender.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/Element-Blazor/Element-Blazor/</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>blazor,Element,admin</PackageTags>
    <Version>0.0.2.1-alpha.1</Version>
    <AssemblyVersion>0.0.2.0</AssemblyVersion>
    <FileVersion>0.0.2.0</FileVersion>
    <UserSecretsId>12e18c4b-b671-4824-8947-019561d8af8b</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="7.0.2" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.17.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Admin\Element.Admin.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\LOGO.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="..\..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="PACKAGE_README.Admin.ServerRender.md">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

</Project>
